name: Train ML (optional)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 2 * * 1'   # 09:30 GMT+7 thứ Hai

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install pandas scikit-learn
      - name: Train ML and export weights
        run: python scripts/train_ml.py
      - name: Commit ML weights
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ml_weights.json || true
          git diff --cached --quiet || git commit -m "Update ML weights"
          git push
